name: Vercel Deploy Hook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        uses: actions/github-script@v7
        env:
          DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
        with:
          script: |
            const core = require('@actions/core')
            const url = process.env.DEPLOY_HOOK_URL
            if (!url) {
              core.setFailed('Missing DEPLOY_HOOK_URL secret')
            } else {
              const res = await fetch(url, { method: 'POST' })
              core.info(`HTTP Status: ${res.status}`)
              if (!res.ok) core.setFailed(`Deploy hook failed with HTTP ${res.status}`)
            }

